package inf.pds.proy.domain.model;

public enum TipoOperacion {
	LISTA_CREADA, LISTA_BUSCADA, LISTAS_OBTENIDAS, LISTA_ELIMINADA, TARJETA_CREADA, TARJETA_BUSCADA, TARJETAS_OBTENIDAS, TARJETA_ELIMINADA, TARJETA_DESPLAZADA, AÑADIR_MIEMBRO, ELIMINAR_MIEMBRO
}
