spring.application.name=PDSProyecto
spring.datasource.url=jdbc:h2:mem:pds_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#h2 nav
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

proy.private.api=/proy/private/v1.0
proy.public.api=/proy/private/v1.0

logging.level.org.hibernate.orm.jdbc.bind=TRACE